# Site settings
title: Moth + Flame
email: your-email@domain.com
description: A Full Service Virtual Reality Agency
baseurl: "/moth-flame/" # the subpath of your site, e.g. /blog/
url: "http://andygillette.com" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown

collections:
  - blog
  - press
